services:
  web:
    build: ./voting-api
    command: bash -c "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0"
    volumes:
      - ./voting-api:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

  sidekiq:
    build: ./voting-api
    command: bundle exec sidekiq
    volumes:
      - ./voting-api:/app
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voting_api_development

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  react-app:
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - web