services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
      
  web:
    build: ./voting-api
    command: bash -c "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0"
    volumes:
      - ./voting-api:/app
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      RAILS_ENV: ${ENV}
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

  sidekiq:
    build: ./voting-api
    command: bundle exec sidekiq
    volumes:
      - ./voting-api:/app
    env_file:
      - ./.env
    environment:
      RAILS_ENV: ${ENV}
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

  react-app:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    depends_on:
      - web