default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  port: 5432
  host: db

development:
  <<: *default
  database: voting_api_development

test:
  <<: *default
  database: voting_api_test

production:
  <<: *default
  database: voting_api_production
  username: voting_api
  password: <%= ENV["VOTING_API_DATABASE_PASSWORD"] %>
