default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: 5432

development:
  <<: *default
  host: db

test:
  <<: *default
  database: voting_api_test
  host: db

production:
  url: <%= ENV['DATABASE_URL'] %>