source 'https://rubygems.org'

ruby '3.1.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 7.1.3', '>= 7.1.3.4'

# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '>= 5.0'

# Add finite state machines to Ruby classes
gem 'aasm'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use Rack Attack to throttle and block abusive requests
gem 'rack-attack'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[ mri mswin mswin64 mingw x64_mingw ]

  # RSpec is a testing tool for Ruby. [https://rspec.info/]
  gem 'rspec-rails'

  # Factory Bot: Library for creating test objects
  gem 'factory_bot_rails'

  # Faker: A library for generating fake data such as names, addresses, and phone numbers
  gem 'faker'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'error_highlight', '>= 0.4.0', platforms: [:ruby]
end

