name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
            --health-cmd "pg_isready -U postgres"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create bundle directory
        run: mkdir -p vendor/bundle

      - name: Cache Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'

      - name: Check Bundler Config
        run: |
          cd voting-api
          bundle config

      - name: Install dependencies
        run: |
          cd voting-api
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4 --retry 3

      - name: Setup Database
        run: |
          cd voting-api
          cp config/database.yml.ci config/database.yml
          RAILS_ENV=test bin/rails db:create db:migrate db:seed db:schema:load

      - name: Run RSpec tests
        run: |
          cd voting-api
          RAILS_ENV=test bundle exec rspec