name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
            --health-cmd "pg_isready -U postgres"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'

      - name: Install dependencies
        run: |
          cd voting-api
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup Database
        run: |
          cd voting-api
          cp config/database.yml.ci config/database.yml
          bin/rails db:create
          bin/rails db:schema:load

      - name: Run RSpec tests
        run: |
          cd voting-api
          bundle exec rspec
